# Generated by Django 4.2 on 2023-05-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_mesta', models.CharField(help_text='Zadej název města', max_length=45, verbose_name='název města')),
                ('kraj', models.CharField(help_text='Zadej název kraje', max_length=45, verbose_name='název kraje')),
                ('psc', models.PositiveSmallIntegerField(verbose_name='PSČ')),
            ],
            options={
                'verbose_name': ('Město',),
                'verbose_name_plural': 'Města',
            },
        ),
        migrations.CreateModel(
            name='zajemce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_zajemce', models.CharField(help_text='Zadej jméno zájemce', max_length=45, verbose_name='jméno zájemce')),
                ('prijmeni_zajemce', models.CharField(help_text='Zadej Příjmení Ošetřovatele', max_length=45, verbose_name='Příjmení Ošetřovatele')),
                ('mobil_zajemce', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mobil')),
                ('email', models.CharField(help_text='Zadej email zájemce', max_length=45, verbose_name='email zájemce')),
                ('mesto_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulek.mesto', verbose_name='Město')),
            ],
            options={
                'verbose_name': ('Zájemce',),
                'verbose_name_plural': 'Zájemci',
            },
        ),
        migrations.CreateModel(
            name='utulek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadej název útulku', max_length=45, verbose_name='název útulku')),
                ('adresa', models.CharField(help_text='Zadej adresu útulku', max_length=45, unique=True, verbose_name='adresa útulku')),
                ('mesto_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulek.mesto', verbose_name='Město')),
            ],
            options={
                'verbose_name': ('Útulek',),
                'verbose_name_plural': 'Útulky',
            },
        ),
        migrations.CreateModel(
            name='pes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_psa', models.CharField(help_text='Zadej jméno psa', max_length=45, verbose_name='jméno psa')),
                ('rasa', models.CharField(help_text='Zadej rasu psa', max_length=45, verbose_name='rasa psa')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='popis')),
                ('utulek_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulek.utulek', verbose_name='Útulek')),
            ],
            options={
                'verbose_name': ('Pes',),
                'verbose_name_plural': 'Psi',
            },
        ),
        migrations.CreateModel(
            name='osetrovatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(help_text='Zadej Jméno Ošetřovatele', max_length=45, verbose_name='Jméno Ošetřovatele')),
                ('prijmeni', models.CharField(help_text='Zadej Příjmení Ošetřovatele', max_length=45, verbose_name='Příjmení Ošetřovatele')),
                ('mobil', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mobil')),
                ('utulek_nazev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utulek.utulek', verbose_name='Útulek název')),
            ],
            options={
                'verbose_name': ('Ošetřovatel',),
                'verbose_name_plural': 'Ošetřovatelé',
            },
        ),
    ]
