# Generated by Django 4.2 on 2023-06-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulek', '0002_utulek_fotografie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='fotografie',
            field=models.ImageField(blank=True, null=True, upload_to='psi', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='mesto',
            name='nazev_mesta',
            field=models.CharField(help_text='Zadej název města', max_length=45, unique=True, verbose_name='název města'),
        ),
    ]
