# Generated by Django 4.2 on 2023-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulek', '0004_pes_vek'),
    ]

    operations = [
        migrations.AddField(
            model_name='pes',
            name='ockovani',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, 'Ano'), (2, 'Ne')], default=0, verbose_name='Očkování'),
        ),
    ]
