# Generated by Django 4.2 on 2023-06-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulek', '0005_pes_ockovani'),
    ]

    operations = [
        migrations.AddField(
            model_name='utulek',
            name='popis',
            field=models.TextField(blank=True, null=True, verbose_name='popis'),
        ),
        migrations.AlterField(
            model_name='pes',
            name='ockovani',
            field=models.CharField(choices=[('ANO', 'Ano'), ('NE', 'Ne')], default=0, max_length=3, verbose_name='Očkování'),
        ),
    ]
