# Generated by Django 4.2 on 2023-06-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulek', '0006_utulek_popis_alter_pes_ockovani'),
    ]

    operations = [
        migrations.AddField(
            model_name='utulek',
            name='cas_do',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='utulek',
            name='cas_od',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='utulek',
            name='mobil',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mobil'),
        ),
    ]
