# Generated by Django 4.2 on 2023-06-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utulek', '0007_utulek_cas_do_utulek_cas_od_utulek_mobil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utulek',
            name='cas_do',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='utulek',
            name='cas_od',
            field=models.TimeField(null=True),
        ),
    ]
