# Generated by Django 4.2 on 2023-06-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utulek', '0008_alter_utulek_cas_do_alter_utulek_cas_od'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesto',
            name='psc',
        ),
    ]
